// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU-RJa2GwYWkMYpQJ3jCVXow7xfOD5sw8',
    appId: '1:61379813134:web:ae1aac64772584a805415f',
    messagingSenderId: '61379813134',
    projectId: 'catataxo-7e38b',
    authDomain: 'catataxo-7e38b.firebaseapp.com',
    storageBucket: 'catataxo-7e38b.firebasestorage.app',
    measurementId: 'G-JDZ92W1401',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD09ZcXq5oMlzdDZUosr0Zvkc-Y9UZDXDo',
    appId: '1:61379813134:android:3834e333bac5bc6b05415f',
    messagingSenderId: '61379813134',
    projectId: 'catataxo-7e38b',
    storageBucket: 'catataxo-7e38b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7aFoHecMPChkAtCUfxKYfXuxblWy-sE0',
    appId: '1:61379813134:ios:c5bc8faa241b099a05415f',
    messagingSenderId: '61379813134',
    projectId: 'catataxo-7e38b',
    storageBucket: 'catataxo-7e38b.firebasestorage.app',
    iosBundleId: 'com.example.catataxo',
  );
}
