# Generated by Django 2.1.3 on 2019-06-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antreg', '0002_auto_20190627_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='especie',
            name='descubridor',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='especie',
            name='fechadescub',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
